CREATE TABLE EMPLEADO
(
    IDEMPLEADO NUMBER(10) NOT NULL,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    DNI VARCHAR2(12) NOT NULL,
    ESTADO_CIVIL VARCHAR2(1) NOT NULL,
    GENERO VARCHAR2(1) NOT NULL,
    EDAD NUMBER(3) NOT NULL
)

SELECT * FROM EMPLEADO;

ALTER TABLE EMPLEADO ADD CONSTRAINT ID_EMPLEADO_PK PRIMARY KEY (IDEMPLEADO);



INSERT INTO EMPLEADO (IDEMPLEADO,NOMBRES,APELLIDOS,DNI,ESTADO_CIVIL,GENERO,EDAD) VALUES("","","","","","","");
/*DROP TABLE EMPLEADO;
*/
